name: Test Matrix value

on:
    push:
    workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: "fsd-form-runner"
  IMAGE_REPO_PATH: "ghcr.io/${{github.repository_owner}}"

jobs:
  copilot_environments_workflow_setup:
    runs-on: ubuntu-latest
    outputs:
      matrix_env: ${{ toJSON(steps.*.outputs.env_list) }}
    steps:
    #   - id: dev
    #     run: |
    #         echo "env_list=dev" >> $GITHUB_OUTPUT
    #   - id: test
    #     run: |
    #         echo "env_list=test" >> $GITHUB_OUTPUT
      - id: array
        run: |
          export TARGETS={"target": ["dev","test"]}
          echo "env_list=$(jq -cn --argjson environments "$TARGETS" '{target: $environments}')" >> $GITHUB_OUTPUT

  docker-build:
    runs-on: ubuntu-latest
    needs: [copilot_environments_workflow_setup]
    steps:
      - name: debug-matrix
        env:
          MATRIX_ENV: ${{ needs.copilot_environments_workflow_setup.outputs.matrix_env }}
        run: |
          echo matrix env is $MATRIX_ENV


  deploy:
    needs: [copilot_environments_workflow_setup]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: ${{ fromJSON( needs.copilot_environments_workflow_setup.outputs.matrix_env ) }}
    steps:

      - name: print matrix
        shell: bash
        run: echo matrix is ${{ matrix.target }}
