name: Test job ordering

on:
    push:
    workflow_dispatch:
      inputs:
        job:
          description: Which job to force
          type: choice
          required: true
          options:
            - one
            - two
            - three

jobs:
  setup_job_list:
    runs-on: ubuntu-latest
    outputs:
      jobs_to_run: ${{ steps.determine_jobs.outputs.job_list }}
    steps:
      - id: determine_jobs
        run: |
          if [ "${{ inputs.job }}" != '' ]; then
            export jobs='["${{ inputs.job }}"]'
          else
            export jobs='["one", "two", "three"]'
          fi
          echo "job_list=$(jq -cn --argjson keys "$jobs" '$keys')" >> $GITHUB_OUTPUT

  debug-info:
    runs-on: ubuntu-latest
    needs: [setup_job_list]
    steps:
      - name: debug-jobs
        env:
          JOB_LIST: ${{ needs.setup_job_list.outputs.jobs_to_run }}
        run: |
          echo list of jobs is $JOB_LIST


  one:
    needs: [setup_job_list]
    runs-on: ubuntu-latest
    if: ${{ contains(fromJSON(needs.setup_job_list.outputs.jobs_to_run), 'one') }}
    steps:
      - name: print job name
        shell: bash
        run: echo On job one

  two:
    needs: [one]
    if: ${{ contains(fromJSON(needs.setup_job_list.outputs.jobs_to_run), 'two') }}
    runs-on: ubuntu-latest
    steps:

      - name: print job name
        shell: bash
        run: echo On job two
